### ISSUE TITLE
New update changes in inventory moving abilities

### ISSUE THREAD

**Issue by RowdyRob72** [Icydeath/ffxi-addon-storemats#1]
This is not a bug or problem of any sort, but with SE's last update, you are able to manually move items from bag to bag withoout having to move them to inventory. I'm not sure if Itemizer has caught onto this, but would it not be much more efficient to do a rewrite to utilize this.

**Comment by Icydeath** [comment]
100% spot on. It's on my list to look into. I just moved it up on the list because I know someone else is interested in it now ^.^
